version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-27-alpha

    working_directory: ~/repo

    environment:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -XX:MaxPermSize=512m"
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "hiroaki-core/build.gradle" }}-{{ checksum "hiroaki-android/build.gradle" }}
      - run:
          name: Update Android SDK
          command: yes | sdkmanager --update || true
      - run:
          name: Install Android SDK Packages
          command: yes | sdkmanager --install "build-tools;27.0.3" "tools" "platform-tools" "platforms;android-27" || true
      - run:
          name: Setup emulator
          command: sdkmanager --install "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}-{{ checksum "hiroaki-core/build.gradle" }}-{{ checksum "hiroaki-android/build.gradle" }}
          paths:
            - ~/.gradle
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel auto -verbose
          background: true
      - run:
          name: Run Klint on app module
          command: ./gradlew :app:ktlint
          when: always
      - run:
          name: Run Klint on hiroaki core module
          command: ./gradlew :hiroaki-core:ktlint
          when: always
      - run:
          name: Run Klint on hiroaki android module
          command: ./gradlew :hiroaki-android:ktlint
          when: always
      - run:
          name: Run Unit Tests
          command: ./gradlew test
          when: always
      - run:
          name: Wait emulator
          command: |
            # wait for it to have booted
            circle-android wait-for-boot
            # unlock the emulator screen
            sleep 30
            adb shell input keyevent 82
      - run:
          name: Run Tests
          command: ./gradlew :app:connectedAndroidTest
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
